### ISSUE TITLE
file_get_contents failed to open stream: HTTP request failed

### ISSUE THREAD

**Issue by stebogit** [iranianpep/darksky#12]
Hey @iranianpep,
I'm having an issue with Darksky API when running my app on Heroku, it always throws this:
```
Severity: Warning --> file_get_contents(https://api.darksky.net/forecast/2b45ce1648***********/47.225451000,-119.956826000,2018-04-10T00:00:00-08:00?lang=en&units=us&exclude=currently%2Cminutely%2Calerts%2Cflags): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway /app/vendor/darksky/darksky/src/Darksky/Darksky.php 83 
```
Sometimes the `HTTP/1.1 502 Bad Gateway` part is not there, so I guess another error type occurs.

Do you have any clue of what might be happening and how to fix it or find a workaround? It basically does not work in there, locally and on the browser the urls (and the library) work fine instead.

**Comment by iranianpep** [comment]
Can you try something? please temporarily wrap the return value of `generateRequestUrl()` (located in Darksky/Darksky.php of your vendor) in `urlencode()` to see if it fixes the issue? If that's the case `file_get_contents` should be called on encoded version of the url.

**Comment by stebogit** [comment]
Sorry @iranianpep for the late reply. It looks like the folks at Darksky fixed the issue, after I contacted them.
Anyway, thanks for the support! 😃

**Comment by iranianpep** [comment]
Thanks for letting me know and am glad it's resolved. If they mentioned the reason and you think it's helpful for others please share it here. Cheers.
