### ISSUE TITLE
`file_get_contents` generates uncatchable warning

### ISSUE THREAD

**Issue by stebogit** [iranianpep/darksky#13]
Hey @iranianpep,
I noticed that the `file_get_contents` function you use to fetch data throws a warning if the source does not exist, for example if the passed url is not reachable for some reason (like in my case).
Unless you [handle warnings with a custom `set_error_handler` ](https://stackoverflow.com/questions/272361/how-can-i-handle-the-warning-of-file-get-contents-function-in-php/3406181#3406181) you basically can't catch this type of error and easily handle the case in which the connection isn't available.

I'd suggest to silence errors when using the function in your code (i.e. `@file_get_contents()`) and check the returned value, if it is `false` throw a `DarkskyException` for connection or fetch error.

**Comment by iranianpep** [comment]
The change has been applied to this release: https://github.com/iranianpep/darksky/tree/v1.4.2

Feel free to reopen this if your issue has not been resolved.

**Comment by stebogit** [comment]
super! 🎉 
thanks @iranianpep
