### ISSUE TITLE
`guzzle/guzzle` dependency

### ISSUE THREAD

**Issue by stebogit** [iranianpep/darksky#7]
Even though it seems to me your library does not have other dependencies, your `composer.lock` for some reason still requires a bunch of dependencies among which `guzzle/guzzle`, which is abandoned:

![screen shot 2017-11-30 at 4 31 59 pm](https://user-images.githubusercontent.com/12717225/33462383-0565e82e-d5ec-11e7-8ce2-bd7d29b9bedc.png)

**Comment by iranianpep** [comment]
Hey @stebogit 

Thanks for spotting this. I'm aware of it and it's because of `codeclimate/php-test-reporter` which is discussed here https://github.com/codeclimate/php-test-reporter/issues/103

I'll fix it shortly and will update you.

Cheers,
Ehsan

**Comment by iranianpep** [comment]
This is fixed in https://github.com/iranianpep/darksky/tree/v1.4 now
